export const PATCH_NOTES_DE = [
  "Patch 3.0: Der Weg bleibt. Nur die Gewohnheit ist weg.",
  "Breaking Change: Komfortzone wurde erfolgreich deprecated.",
  "Hotfix: Der sichere Pfad war ein Missverständnis.",
  "Wandel-Update: Wenn es wackelt, bist du am richtigen Level.",
  "Changelog: Aus Abkürzung wurde Entscheidung.",
  "Reorg: Umwege liefern heute Extra-Punkte.",
  "Stabilitätsfix: Stillstand verursachte Absturz. Behoben.",
  "Patch Notes: Karte neu. Kopf frei.",
  "Mini-Update: Manche Wände haben den Arbeitsplatz gewechselt.",
  "Hotfix: Routine ist jetzt optional.",
  "Release: Neue Kurven. Alte Ausreden entfernt.",
  "Wandel-Modus: Plan A bleibt. Plan B bootet schneller.",
  "Patch 1.0: Orientierung aktualisiert. Panik bleibt Beta.",
  "Micro-Patch: Aus \"muss\" wurde \"kann\".",
  "Reorg: Der Ausgang ist gleich. Der Zugang nicht.",
  "Hotfix: Geister von gestern wurden umgestellt.",
  "Patch Notes: Links fühlt sich heute wie rechts an - atme.",
  "Changelog: Mut skaliert jetzt automatisch mit Chaos.",
  "Layout-Tuning: Geradeaus ist überbewertet.",
  "Breaking Change: Kontrolle nur noch in kleinen Portionen.",
  "Patch 2.7: Wer stoppt, wird überholt - vom Wandel.",
  "Hotfix: Sicherheit wurde um zwei Felder verschoben.",
  "Reorg: Der Standardweg macht heute Sabbatical.",
  "Wandel-Update: Du darfst dich umentscheiden. Die Karte auch.",
  "Patch Notes: Neue Regeln, gleiche Mission: weitergehen.",
  "Micro-Patch: Ein Korridor wurde zur Frage.",
  "Release Candidate: Vertrauen ist schneller als Zweifel.",
  "Hotfix: Erwartungen neu kalibriert. Realität lädt nach.",
  "Changelog: Aus \"später\" wurde \"jetzt\".",
  "Patch 4.1: Das Unbekannte ist nicht gefährlich - nur neu.",
  "Wandel-Update: Wenn's eng wird, denk quer.",
  "Reorg: Wir haben Platz geschaffen. Für Bewegung.",
  "Patch Notes: Punkte liegen jetzt dort, wo du nicht suchst.",
  "Hotfix: Hinter jeder Ecke könnte eine Idee warten.",
  "Breaking Change: Perfekt wurde durch spielbar ersetzt.",
  "Mini-Update: Aus Sackgasse wurde Perspektive.",
  "Changelog: Intuition hat ein Upgrade bekommen.",
  "Patch 5.0: Veränderung ist nicht das Problem - Festhalten schon.",
  "Hotfix: Erst bewegen, dann verstehen.",
  "Release Notes: Du bist noch du. Nur flexibler."
] as const;
